// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: crawlerd.proto

package crawlerdpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Interval int64  `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
}

func (x *RequestURL) Reset() {
	*x = RequestURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crawlerd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestURL) ProtoMessage() {}

func (x *RequestURL) ProtoReflect() protoreflect.Message {
	mi := &file_crawlerd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestURL.ProtoReflect.Descriptor instead.
func (*RequestURL) Descriptor() ([]byte, []int) {
	return file_crawlerd_proto_rawDescGZIP(), []int{0}
}

func (x *RequestURL) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestURL) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestURL) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

type RequestDeleteURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RequestDeleteURL) Reset() {
	*x = RequestDeleteURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crawlerd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeleteURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteURL) ProtoMessage() {}

func (x *RequestDeleteURL) ProtoReflect() protoreflect.Message {
	mi := &file_crawlerd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteURL.ProtoReflect.Descriptor instead.
func (*RequestDeleteURL) Descriptor() ([]byte, []int) {
	return file_crawlerd_proto_rawDescGZIP(), []int{1}
}

func (x *RequestDeleteURL) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ResponseURL struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResponseURL) Reset() {
	*x = ResponseURL{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crawlerd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseURL) ProtoMessage() {}

func (x *ResponseURL) ProtoReflect() protoreflect.Message {
	mi := &file_crawlerd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseURL.ProtoReflect.Descriptor instead.
func (*ResponseURL) Descriptor() ([]byte, []int) {
	return file_crawlerd_proto_rawDescGZIP(), []int{2}
}

type TopicMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *TopicMessage) Reset() {
	*x = TopicMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crawlerd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicMessage) ProtoMessage() {}

func (x *TopicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_crawlerd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicMessage.ProtoReflect.Descriptor instead.
func (*TopicMessage) Descriptor() ([]byte, []int) {
	return file_crawlerd_proto_rawDescGZIP(), []int{3}
}

func (x *TopicMessage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TopicMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_crawlerd_proto protoreflect.FileDescriptor

var file_crawlerd_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0a, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x70, 0x62, 0x22, 0x4a, 0x0a, 0x0a,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x22, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x0d, 0x0a, 0x0b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x34, 0x0a, 0x0c, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x32, 0xcb, 0x01, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x3b, 0x0a, 0x06,
	0x41, 0x64, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x1a, 0x17,
	0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x1a, 0x17,
	0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x1c, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72,
	0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x52, 0x4c, 0x1a, 0x17, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x00, 0x32,
	0xce, 0x01, 0x0a, 0x09, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x12, 0x3b, 0x0a,
	0x06, 0x41, 0x64, 0x64, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x1a,
	0x17, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x16, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x52, 0x4c, 0x1a,
	0x17, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x09, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x52, 0x4c, 0x12, 0x1c, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65,
	0x72, 0x64, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x52, 0x4c, 0x1a, 0x17, 0x2e, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x52, 0x4c, 0x22, 0x00,
	0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x63, 0x72, 0x61, 0x77, 0x6c, 0x65, 0x72, 0x64, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_crawlerd_proto_rawDescOnce sync.Once
	file_crawlerd_proto_rawDescData = file_crawlerd_proto_rawDesc
)

func file_crawlerd_proto_rawDescGZIP() []byte {
	file_crawlerd_proto_rawDescOnce.Do(func() {
		file_crawlerd_proto_rawDescData = protoimpl.X.CompressGZIP(file_crawlerd_proto_rawDescData)
	})
	return file_crawlerd_proto_rawDescData
}

var file_crawlerd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_crawlerd_proto_goTypes = []interface{}{
	(*RequestURL)(nil),       // 0: crawlerdpb.RequestURL
	(*RequestDeleteURL)(nil), // 1: crawlerdpb.RequestDeleteURL
	(*ResponseURL)(nil),      // 2: crawlerdpb.ResponseURL
	(*TopicMessage)(nil),     // 3: crawlerdpb.TopicMessage
}
var file_crawlerd_proto_depIdxs = []int32{
	0, // 0: crawlerdpb.Worker.AddURL:input_type -> crawlerdpb.RequestURL
	0, // 1: crawlerdpb.Worker.UpdateURL:input_type -> crawlerdpb.RequestURL
	1, // 2: crawlerdpb.Worker.DeleteURL:input_type -> crawlerdpb.RequestDeleteURL
	0, // 3: crawlerdpb.Scheduler.AddURL:input_type -> crawlerdpb.RequestURL
	0, // 4: crawlerdpb.Scheduler.UpdateURL:input_type -> crawlerdpb.RequestURL
	1, // 5: crawlerdpb.Scheduler.DeleteURL:input_type -> crawlerdpb.RequestDeleteURL
	2, // 6: crawlerdpb.Worker.AddURL:output_type -> crawlerdpb.ResponseURL
	2, // 7: crawlerdpb.Worker.UpdateURL:output_type -> crawlerdpb.ResponseURL
	2, // 8: crawlerdpb.Worker.DeleteURL:output_type -> crawlerdpb.ResponseURL
	2, // 9: crawlerdpb.Scheduler.AddURL:output_type -> crawlerdpb.ResponseURL
	2, // 10: crawlerdpb.Scheduler.UpdateURL:output_type -> crawlerdpb.ResponseURL
	2, // 11: crawlerdpb.Scheduler.DeleteURL:output_type -> crawlerdpb.ResponseURL
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crawlerd_proto_init() }
func file_crawlerd_proto_init() {
	if File_crawlerd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_crawlerd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crawlerd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeleteURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crawlerd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseURL); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crawlerd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crawlerd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_crawlerd_proto_goTypes,
		DependencyIndexes: file_crawlerd_proto_depIdxs,
		MessageInfos:      file_crawlerd_proto_msgTypes,
	}.Build()
	File_crawlerd_proto = out.File
	file_crawlerd_proto_rawDesc = nil
	file_crawlerd_proto_goTypes = nil
	file_crawlerd_proto_depIdxs = nil
}
