---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: localhost:5000/crawlerd/api:latest
          imagePullPolicy: IfNotPresent
          command: [ "./app", "--mongo-host=mongo.default.svc.cluster.local", "--mongo-port=27017","--scheduler-addr=scheduler.default.svc.cluster.local:9888" ]
          name: api
          env:
            - name: DEBUG
              value: "1"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccountName: crawlerd
      containers:
        - image: localhost:5000/crawlerd/scheduler:latest
          imagePullPolicy: IfNotPresent
          command: [ "./app", "--worker-port=9338", "--mongo-host=mongo.default.svc.cluster.local", "--mongo-port=27017", "--etcd-addr=etcd.default.svc.cluster.local:2379", "--grpc-addr=:9888", "--k8s-namespace=default", "--k8s-worker-selector=app=worker" ]
          name: scheduler
          env:
            - name: DEBUG
              value: "1"
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      serviceAccountName: crawlerd
      containers:
        - image: localhost:5000/crawlerd/worker:latest
          imagePullPolicy: IfNotPresent
          command: [ "./app", "--port=9338", "--mongo-host=mongo.default.svc.cluster.local", "--mongo-port=27017", "--etcd-addr=etcd.default.svc.cluster.local:2379", "--scheduler-addr=scheduler.default.svc.cluster.local:9888", "--k8s-namespace=default", "--k8s-worker-selector=app=worker" ]
          name: worker
          env:
            - name: DEBUG
              value: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: scheduler
spec:
  type: NodePort
  selector:
    app: scheduler
  ports:
    - port: 9888
      nodePort: 31019
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crawlerd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: get-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-pods
subjects:
  - kind: ServiceAccount
    name: crawlerd
